# Generated by Django 2.2 on 2020-01-28 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='download.jpeg', upload_to='profile_pics'),
        ),
    ]
